### PR TITLE
CCN Assignment

### PR DESCRIPTION
**Pull request by kekene48**

### CODE REVIEW

**Comment by kekene48** [comment]
My CCN Assignment

**Comment by seunbayo** [comment]
Hi @kekene48 please resolve conflicting files

**Comment by kekene48** [comment]
Good morning, Done that  Sent from Mail for Windows 10 From: seunbayoSent: Thursday, June 1, 2023 10:50 PMTo: seunbayo/CCN-2023CH1Cc: kekene48; MentionSubject: Re: [seunbayo/CCN-2023CH1] CCN Assignment (PR #6) Hi @kekene48 please resolve conflicting files—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by kekene48** [comment]
Sorry, I don't understand

**Pull request merged**
